<?php

namespace KitchenRun\Inc\Common\Model;


use DateTime;
use WP_User;

/**
 * Class Event
 * Model of a Event that is saved in the Database or newly created.
 *
 * @since       1.0.0
 * @package     KitchenRun\Inc\Common\Model
 * @author      Niklas Loos <niklas.loos@live.com>
 */
class Event
{

    /**
     * Format that is uses for dates in the Database.
     *
     * @since   1.0.0
     * @var     string  DATE_FORMAT
     */
    const DATE_FORMAT = 'Y-m-d H:i:s';

    /**
     * ID of the Event. Autogenerated by the DB.
     *
     * @since   1.0.0
     * @access  private
     * @var     int $id
     */
    private $id;

    /**
     * Name of the Event.
     *
     * @since   1.0.0
     * @access  private
     * @var     string $name
     */
    private $name;

    /**
     * Is it the current Event.
     * '0' -> not current
     * '1' -> current
     *
     * @since   1.0.0
     * @access  private
     * @var     int $current
     */
    private $current;

    /**
     * Date on which the singup form will be opened.
     * Format: See DATE_FORMAT.
     *
     * @since   1.0.0
     * @access  private
     * @var     string $opening_date
     */
    private $opening_date;

    /**
     * Date on which the singup form will be closed.
     * Format: See DATE_FORMAT.
     *
     * @since   1.0.0
     * @access  private
     * @var     string $closing_date
     */
    private $closing_date;

    /**
     * Date on which the event will take place.
     * Format: See DATE_FORMAT.
     *
     * @since   1.0.0
     * @access  private
     * @var     string $event_date
     */
    private $event_date;

    /**
     * Wordpress User ID of the manager of the event.
     * Normally the User who created the event.
     *
     * @since   1.0.0
     * @access  private
     * @var     int $manager
     */
    private $manager;

    /**
     * Are the Event Teams already paired?
     * '0' -> no
     * '1' -> yes
     *
     * @since   1.0.0
     * @access  private
     * @var     int $paired
     */
    private $paired;


    /**
     * Get Event ID.
     *
     * @since   1.0.0
     * @return  int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Get Event Name.
     *
     * @since   1.0.0
     * @return  string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set Event Name
     *
     * @since   1.0.0
     * @param   string $name
     */
    public function setName($name)
    {
        $this->name = $name;
    }

    /**
     * Is this the current Event?
     * '0' -> no
     * '1' -> yes
     *
     * @since   1.0.0
     * @return  int
     */
    public function getCurrent()
    {
        return $this->current;
    }

    /**
     * Set whether this is the current event.
     * '0' -> not current
     * '1' -> current
     *
     * @since   1.0.0
     * @param   int $current
     */
    public function setCurrent($current)
    {
        $this->current = $current;
    }

    /**
     * Get the Opening Date for the sign up.
     *
     * @since   1.0.0
     * @return  DateTime
     */
    public function getOpeningDate()
    {
        try {
            return new \DateTime($this->opening_date);
        } catch (\Exception $e) {
        }
    }

    /**
     * Set Opening Date for the sign up. String should be in the DATE_FORMAT.
     *
     * @since   1.0.0
     * @param   DateTime|string $opening_date
     */
    public function setOpeningDate($opening_date)
    {
        if ($opening_date instanceof \DateTime) {
            $this->opening_date = $opening_date->format(self::DATE_FORMAT);
        } else {
            $this->opening_date = $opening_date;
        }
    }

    /**
     * Get the Closing Date for the sign up.
     *
     * @since   1.0.0
     * @return  DateTime
     */
    public function getClosingDate()
    {

        try {
            return new \DateTime($this->closing_date);
        } catch (\Exception $e) {
        }
    }

    /**
     * Set Closing Date for the sign up. String should be in the DATE_FORMAT.
     *
     * @since   1.0.0
     * @param   DateTime|string $closing_date
     */
    public function setClosingDate($closing_date)
    {
        if ($closing_date instanceof \DateTime) {
            $this->closing_date = $closing_date->format(self::DATE_FORMAT);
        } else {
            $this->closing_date = $closing_date;
        }
    }

    /**
     * Get the Date of the event.
     *
     * @since   1.0.0
     * @return  DateTime
     */
    public function getEventDate()
    {
        try {
            return new \DateTime($this->event_date);
        } catch (\Exception $e) {
        }
    }

    /**
     * Set Event Date. String should be in the DATE_FORMAT.
     *
     * @since   1.0.0
     * @param   DateTime|string $event_date
     */
    public function setEventDate($event_date)
    {
        if ($event_date instanceof \DateTime) {
            $this->event_date = $event_date->format(self::DATE_FORMAT);
        } else {
            $this->event_date = $event_date;
        }
    }

    /**
     * Get Manager of the Event as Wordpress User.
     *
     * @since   1.0.0
     * @return  WP_User
     */
    public function getManager()
    {
        /** @var WP_User $userdata */
        $userdata = WP_User::get_data_by( 'ID', $this->manager );

        return $userdata;
    }

    /**
     * Set Manager of the Event, should be Wordpress User.
     *
     * @since   1.0.0
     * @param   WP_User $manager
     */
    public function setManager($manager)
    {
        $this->manager = $manager->ID;
    }

    /**
     * Are the Teams of the Event already paired.
     * '0' -> no
     * '1' -> yes
     *
     * @since   1.0.0
     * @return  int
     */
    public function getPaired() {
        return $this->paired;
    }

    /**
     * Set the Pair Status of the Event.
     * '0' -> not paired
     * '1' -> paired
     *
     * @since   1.0.0
     * @param   int $bool
     */
    public function setPaired($bool) {
        $this->paired = $bool;
    }


    /**
     * Find a Event in the Database through the id.
     *
     * @since   1.0.0
     * @param   int     $id     Event ID
     * @return  Event   $event  Event Object
     */
    public static function findbyId($id)
    {
        global $wpdb;

        $table = Database::DB_EVENT_NAME;
        $databaseName =  DB_NAME;
        $prefix = $wpdb->prefix;

        // sql query find row with id
        $sql = "
        SELECT * FROM $databaseName.$prefix$table WHERE id='$id';
    ";

        $event = new Event();

        $row = $wpdb->get_row($sql); // execute sql query

        //create team object
        $event->id = $row->id;
        $event->setName($row->name);
        $event->setCurrent($row->current);
        $event->setOpeningDate($row->opening_date);
        $event->setClosingDate($row->closing_date);
        $event->setEventDate($row->event_date);
        $event->setManager(WP_User::get_data_by( 'ID', $row->manager ));
        $event->setPaired($row->paired);

        return $event;
    }

    /**
     * Find the Current Event in Database.
     *
     * @since   1.0.0
     * @return  Event   $event  Event Object
     */
    public static function findCurrent() {
        global $wpdb;

        $table = Database::DB_EVENT_NAME;
        $databaseName =  DB_NAME;
        $prefix = $wpdb->prefix;

        // sql query find row with id
        $sql = "
        SELECT * FROM $databaseName.$prefix$table WHERE current='1';
        ";

        $event = new Event();

        $row = $wpdb->get_row($sql); // execute sql query

        //create team object
        $event->id = $row->id;
        $event->setName($row->name);
        $event->setCurrent($row->current);
        $event->setOpeningDate($row->opening_date);
        $event->setClosingDate($row->closing_date);
        $event->setEventDate($row->event_date);
        $event->setManager(WP_User::get_data_by( 'ID', $row->manager ));
        $event->setPaired($row->paired);

        return $event;
    }

    /**
     * Find all Events saved in the Database and save them in an Event Array.
     *
     * @since   1.0.0
     * @return  Event[] $event  Array of Event Object
     */
    public static function findAll() {
        global $wpdb;

        $table = Database::DB_EVENT_NAME;
        $databaseName =  DB_NAME;
        $prefix = $wpdb->prefix;

        // sql query
        $sql = "
            SELECT * FROM $databaseName.$prefix$table ;
        ";

        $results = $wpdb->get_results($sql); // execute sql query

        $events = array();

        // create each team object
        foreach ($results as $row) {
            //create team object
            $event = new Event();
            $event->id = $row->id;
            $event->setName($row->name);
            $event->setCurrent($row->current);
            $event->setOpeningDate($row->opening_date);
            $event->setClosingDate($row->closing_date);
            $event->setEventDate($row->event_date);
            $event->setManager(WP_User::get_data_by( 'ID', $row->manager ));
            $event->setPaired($row->paired);

            $events[] = $event;

        }

        return $events;
    }

    /**
     * Saves object in database table
     *
     * @since 1.0.0
     */
    public function save() {
        global $wpdb;

        // wp_kr_team
        $table_name = $wpdb->prefix . Database::DB_EVENT_NAME;

        $col = array(
            'name' => $this->name,
            'event_date' => $this->event_date,
            'opening_date' => $this->opening_date,
            'closing_date' => $this->closing_date,
            'manager' => $this->manager,
            'current' => $this->current,
            'paired' => $this->paired,
        );

        // Format of each column (%s = String, %d = Number)
        $format = array(
            '%s',
            '%s',
            '%s',
            '%s',
            '%d',
            '%d',
            '%d',
        );

        if ($this->id !== NULL) { // is id already set
            $col['id'] = $this->id;
            $format[] = '%d';

            $wpdb->replace($table_name, $col, $format);

        } else {

            // save team in database
            $wpdb->insert(
                $table_name,
                $col,
                $format
            );
        }

    }

    /**
     * Deletes object from database.
     *
     * @since 1.0.0
     */
    public function delete()
    {
        global $wpdb;
        $table_name = $wpdb->prefix . Database::DB_EVENT_NAME;

        $wpdb->delete( $table_name, array( 'id' => $this->id ) );

    }

}